[package]
org = "puneetmakwana"
name = "data_service"
version = "0.1.0"
distribution = "2201.3.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"

[[platform.java11.dependency]]
path = "./lib/mysql-connector-java-8.0.26.jar"